version: '3'
services:
  cqlsh1:
    image: datastax/dse-tools:6.8.16-ubi7
    container_name: cqlsh1
    command: cqlsh <IP контейнера  на машине A>
   
  cqlsh2:
    image: datastax/dse-tools:6.8.16-ubi7
    container_name: cqlsh2
    command: cqlsh <IP контейнера на машине A>
    
  cqlsh3:
    image: datastax/dse-tools:6.8.16-ubi7
    container_name: cqlsh3
    command: cqlsh <IP контейнера на машине A>
