version: '3'
services:
  cqlsh:
    image: datastax/dse-tools:6.8.16-ubi7 # Контейнер cqlsh образ datastax/dse-tools:6.8.16-ubi7
    container_name: CQLSH # имя контейнера CQLSH
    command: cqlsh node2 # подлючения к узлу node2
    
    
networks:
  default:
    external:
      name: bridge	
